import { StyleSheet } from "react-native";

export default StyleSheet.create({
  topPanel: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: "#3f51b5",
  },
  addReminderBody: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fafafa",
    borderRadius: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 1,
  },
  addReminderH1: {
    flexGrow: 1,
    textAlign: "center",
    fontSize: 24, // Roughly equivalent to 1.5em
    color: "#fafafa",
  },
  leftIcon: {
    flexDirection: "row",
    alignItems: "center",
  },
  rightIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  textButtons: {
    textDecorationLine: "none",
    color: "#3f51b5",
    backgroundColor: "#fafafa",
    padding: 3,
    paddingLeft: 7,
    paddingRight: 7,
    borderRadius: 5,
  },
  textInput: {
    width: "100%",
    padding: 10,
    marginTop: 10,
    marginBottom: 10,
    borderWidth: 0,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 1,
    fontSize: 16,
    backgroundColor: "#fafafa",
  },
  sendButton: {
    backgroundColor: "#3f51b5",
    color: "#fff",
    borderWidth: 0,
    borderRadius: 4,
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
    marginTop: 20,
  },
  imagePreview: {
    width: "70%",
    padding: 10,
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fafafa",
  },
  imagePreviewImage: {
    height: 200,
    width: 200,
    resizeMode: "contain",
    shadowColor: "#3f51b5",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    borderRadius: 4,
  },
  upgradePopupOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    alignItems: "center",
    zIndex: 9999,
  },
  upgradePopup: {
    width: "90%",
    maxWidth: 500,
    backgroundColor: "white",
    borderRadius: 4,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    alignItems: "center",
    height: "80%",
  },
  upgradePopupTitle: {
    fontSize: 24,
    marginBottom: 25,
    marginTop: 10,
    fontWeight: "bold",
  },
  closeButton: {
    position: "absolute",
    top: 10,
    right: 10,
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: 20,
  },
  closeButtonText: {
    color: "#aaa",
    fontSize: 28,
    fontWeight: "bold",
    padding: 5,
  },
  gallery: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 20,
  },
  card: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 1,
    borderRadius: 4,
    position: "relative",
  },
  cardImage: {
    width: "100%",
    height: undefined,
    aspectRatio: 1,
    resizeMode: "cover",
  },
  viewPastButton: {
    marginTop: 10,
    backgroundColor: "#3f51b5",
    color: "#fff",
    borderWidth: 0,
    borderRadius: 4,
    padding: 10,
    paddingLeft: 20,
    paddingRight: 20,
  },
  topButtons: {
    position: "absolute",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
  },
  deleteButton: {
    backgroundColor: "#ffffff",
    borderWidth: 0,
    padding: 2,
    width: 30,
    height: 30,
    right: 10,
    top: -10,
    marginRight: 1,
    borderRadius: 15,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 1,
  },
  buttonText: {
    color: "white",
  },
  picker: {
    width: "75%",
    marginVertical: 10,
    borderWidth: 0,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    fontSize: 16,
    backgroundColor: "#fafafa",
  },
  label: {
    fontSize: 16,
  },
  input: {
    width: "100%",
    alignItems: "center",
    padding: 10,
    marginVertical: 10,
    borderWidth: 0,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    fontSize: 16,
    backgroundColor: "#fafafa",
  },
});
